### ISSUE TITLE
Claudia No application icons on fedora jam 25

### ISSUE THREAD

**Issue by Brizfer** [falkTX/falktx-web#1]
Hi everyone, I'm french and I'm a musician...
Here's my issue : I installed cadence (Cadence-1.0.0.92034ff-2.fc25.x86_64) for fedora jam 25 (kernel-rt-4.9.11-100.rt9.1.fc24.ccrma.x86_64) from the ycollet site "https : //copr.fedorainfracloud.org/coprs/ycollet/linuxmao/ ". Everything goes well except claudia (version 0.8.1) which does not load the icons (daw, plugins, effects, etc ...) of the applications menu, but the command "Run Custom .." works ... I created some studios. I tried the various tips of the net remained without results ... I have no error message if I run in konsole mode. Is this a known problem? How can I find my icons applications?
Currently, I use xfce4 as windows manager. Should I change it ? Thank you for your help. 

Brizfer

**Comment by falkTX** [comment]
this is really not the place to report such issue.
open one on the cadence project.
this one is for my own personal website...

**Comment by Brizfer** [comment]
Hi falkTX i'm so sorry. I do it in a row...
